# Generated by Django 3.0.5 on 2020-07-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_auto_20200711_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='created_by',
        ),
    ]
